server:
  port: ${port:10003}

spring:
  datasource:
    driver-class=name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/provider?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
    schema: classpath:db/schema-mysql.sql
    data: classpath:db/data-mysql.sql

  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
      discovery:
        server-addr: 127.0.0.1:8848

  application:
    name: provider-service-prl



